export default [{"root":"C","name":"major","notes":"C E G","common":true},
{"root":"C#","name":"major","notes":"C# F G#"},
{"root":"D","name":"major","notes":"D F# A","common":true},
{"root":"Eb","name":"major","notes":"Eb G Bb"},
{"root":"E","name":"major","notes":"E G# B","common":true},
{"root":"F","name":"major","notes":"F A C","common":true},
{"root":"F#","name":"major","notes":"F# A# C#"},
{"root":"G","name":"major","notes":"G B D","common":true},
{"root":"Ab","name":"major","notes":"Ab C Eb"},
{"root":"A","name":"major","notes":"A C# E","common":true},
{"root":"Bb","name":"major","notes":"Bb D F"},
{"root":"B","name":"major","notes":"B D# F#"},
{"root":"C","name":"minor","notes":"C Eb G"},
{"root":"C#","name":"minor","notes":"C# E G#"},
{"root":"D","name":"minor","notes":"D F A","common":true},
{"root":"Eb","name":"minor","notes":"Eb Gb Bb"},
{"root":"E","name":"minor","notes":"E G B","common":true},
{"root":"F","name":"minor","notes":"F Ab C"},
{"root":"F#","name":"minor","notes":"F# A C#"},
{"root":"G","name":"minor","notes":"G Bb D"},
{"root":"Ab","name":"minor","notes":"Ab B Eb"},
{"root":"A","name":"minor","notes":"A C E","common":true},
{"root":"Bb","name":"minor","notes":"Bb Db F"},
{"root":"B","name":"minor","notes":"B D F#"},
{"root":"C","name":"diminished","notes":"C Eb Gb"},
{"root":"C#","name":"diminished","notes":"C# E G"},
{"root":"D","name":"diminished","notes":"D F Ab"},
{"root":"Eb","name":"diminished","notes":"Eb Gb A"},
{"root":"E","name":"diminished","notes":"E G Bb"},
{"root":"F","name":"diminished","notes":"F Ab B"},
{"root":"F#","name":"diminished","notes":"F# A C"},
{"root":"G","name":"diminished","notes":"G Bb Db"},
{"root":"Ab","name":"diminished","notes":"Ab B D"},
{"root":"A","name":"diminished","notes":"A C Eb"},
{"root":"Bb","name":"diminished","notes":"Bb Db E"},
{"root":"B","name":"diminished","notes":"B D F"},
{"root":"C","name":"diminished seventh","notes":"C Eb Gb A"},
{"root":"C#","name":"diminished seventh","notes":"C# E G Bb"},
{"root":"D","name":"diminished seventh","notes":"D F Ab B"},
{"root":"Eb","name":"diminished seventh","notes":"Eb Gb A Dbb C"},
{"root":"E","name":"diminished seventh","notes":"E G Bb Db"},
{"root":"F","name":"diminished seventh","notes":"F Ab B D"},
{"root":"F#","name":"diminished seventh","notes":"F# A C Eb"},
{"root":"G","name":"diminished seventh","notes":"G Bb Db E"},
{"root":"Ab","name":"diminished seventh","notes":"Ab B D F"},
{"root":"A","name":"diminished seventh","notes":"A C Eb Gb"},
{"root":"Bb","name":"diminished seventh","notes":"Bb Db E G"},
{"root":"B","name":"diminished seventh","notes":"B D F Ab"},
{"root":"C","name":"augmented","notes":"C E G#"},
{"root":"C#","name":"augmented","notes":"C# F A"},
{"root":"D","name":"augmented","notes":"D F# A#"},
{"root":"Eb","name":"augmented","notes":"Eb G B"},
{"root":"E","name":"augmented","notes":"E G# C"},
{"root":"F","name":"augmented","notes":"F A C#"},
{"root":"F#","name":"augmented","notes":"F# A# D"},
{"root":"G","name":"augmented","notes":"G B D#"},
{"root":"Ab","name":"augmented","notes":"Ab C E"},
{"root":"A","name":"augmented","notes":"A C# F"},
{"root":"Bb","name":"augmented","notes":"Bb D F#"},
{"root":"B","name":"augmented","notes":"B D# G"},
{"root":"C","name":"dominant seventh","notes":"C E G Bb","common":true},
{"root":"C#","name":"dominant seventh","notes":"C# F G# B"},
{"root":"D","name":"dominant seventh","notes":"D F# A C","common":true},
{"root":"Eb","name":"dominant seventh","notes":"Eb G Bb Db"},
{"root":"E","name":"dominant seventh","notes":"E G# B D","common":true},
{"root":"F","name":"dominant seventh","notes":"F A C Eb"},
{"root":"F#","name":"dominant seventh","notes":"F# A# C# E"},
{"root":"G","name":"dominant seventh","notes":"G B D F","common":true},
{"root":"Ab","name":"dominant seventh","notes":"Ab C Eb Gb"},
{"root":"A","name":"dominant seventh","notes":"A C# E G","common":true},
{"root":"Bb","name":"dominant seventh","notes":"Bb D F Ab"},
{"root":"B","name":"dominant seventh","notes":"B D# F# A","common":true},
{"root":"C","name":"minor seventh","notes":"C Eb G Bb"},
{"root":"C#","name":"minor seventh","notes":"C# E G# B"},
{"root":"D","name":"minor seventh","notes":"D F A C","common":true},
{"root":"Eb","name":"minor seventh","notes":"Eb Gb Bb Db"},
{"root":"E","name":"minor seventh","notes":"E G B D"},
{"root":"F","name":"minor seventh","notes":"F Ab C Eb"},
{"root":"F#","name":"minor seventh","notes":"F# A C# E"},
{"root":"G","name":"minor seventh","notes":"G Bb D F"},
{"root":"Ab","name":"minor seventh","notes":"Ab B Eb Gb"},
{"root":"A","name":"minor seventh","notes":"A C E G","common":true},
{"root":"Bb","name":"minor seventh","notes":"Bb Db F Ab"},
{"root":"B","name":"minor seventh","notes":"B D F# A"},
{"root":"C","name":"major seventh","notes":"C E G B","common":true},
{"root":"C#","name":"major seventh","notes":"C# F G# C"},
{"root":"D","name":"major seventh","notes":"D F# A C#"},
{"root":"Eb","name":"major seventh","notes":"Eb G Bb D"},
{"root":"E","name":"major seventh","notes":"E G# B D#"},
{"root":"F","name":"major seventh","notes":"F A C E","common":true},
{"root":"F#","name":"major seventh","notes":"F# A# C# F"},
{"root":"G","name":"major seventh","notes":"G B D F#"},
{"root":"Ab","name":"major seventh","notes":"Ab C Eb G"},
{"root":"A","name":"major seventh","notes":"A C# E G#","common":true},
{"root":"Bb","name":"major seventh","notes":"Bb D F A"},
{"root":"B","name":"major seventh","notes":"B D# F# A#"},
{"root":"C","name":"major sixth","notes":"C E G A"},
{"root":"C#","name":"major sixth","notes":"C# F G# A#"},
{"root":"D","name":"major sixth","notes":"D F# A B"},
{"root":"Eb","name":"major sixth","notes":"Eb G Bb C"},
{"root":"E","name":"major sixth","notes":"E G# B C#"},
{"root":"F","name":"major sixth","notes":"F A C D"},
{"root":"F#","name":"major sixth","notes":"F# A# C# D#"},
{"root":"G","name":"major sixth","notes":"G B D E"},
{"root":"Ab","name":"major sixth","notes":"Ab C Eb F"},
{"root":"A","name":"major sixth","notes":"A C# E F#"},
{"root":"Bb","name":"major sixth","notes":"Bb D F G"},
{"root":"B","name":"major sixth","notes":"B D# F# G#"},
{"root":"C","name":"minor sixth","notes":"C Eb G A"},
{"root":"C#","name":"minor sixth","notes":"C# E G# A#"},
{"root":"D","name":"minor sixth","notes":"D F A B"},
{"root":"Eb","name":"minor sixth","notes":"Eb Gb Bb C"},
{"root":"E","name":"minor sixth","notes":"E G B C#"},
{"root":"F","name":"minor sixth","notes":"F Ab C D"},
{"root":"F#","name":"minor sixth","notes":"F# A C# D#"},
{"root":"G","name":"minor sixth","notes":"G Bb D E"},
{"root":"Ab","name":"minor sixth","notes":"Ab B Eb F"},
{"root":"A","name":"minor sixth","notes":"A C E F#"},
{"root":"Bb","name":"minor sixth","notes":"Bb Db F G"},
{"root":"B","name":"minor sixth","notes":"B D F# G#"},
{"root":"C","name":"seventh sharp five","notes":"C E G# Bb"},
{"root":"C#","name":"seventh sharp five","notes":"C# F A B"},
{"root":"D","name":"seventh sharp five","notes":"D F# A# C"},
{"root":"Eb","name":"seventh sharp five","notes":"Eb G B Db"},
{"root":"E","name":"seventh sharp five","notes":"E G# C D"},
{"root":"F","name":"seventh sharp five","notes":"F A C# Eb"},
{"root":"F#","name":"seventh sharp five","notes":"F# A# D E"},
{"root":"G","name":"seventh sharp five","notes":"G B D# F"},
{"root":"Ab","name":"seventh sharp five","notes":"Ab C E Gb"},
{"root":"A","name":"seventh sharp five","notes":"A C# F G"},
{"root":"Bb","name":"seventh sharp five","notes":"Bb D F# Ab"},
{"root":"B","name":"seventh sharp five","notes":"B D# G A"},
{"root":"C","name":"seventh flat five","notes":"C E Gb Bb"},
{"root":"C#","name":"seventh flat five","notes":"C# F G B"},
{"root":"D","name":"seventh flat five","notes":"D F# Ab C"},
{"root":"Eb","name":"seventh flat five","notes":"Eb G A Db"},
{"root":"E","name":"seventh flat five","notes":"E G# Bb D"},
{"root":"F","name":"seventh flat five","notes":"F A B Eb"},
{"root":"F#","name":"seventh flat five","notes":"F# A# C E"},
{"root":"G","name":"seventh flat five","notes":"G B Db F"},
{"root":"Ab","name":"seventh flat five","notes":"Ab C D Gb"},
{"root":"A","name":"seventh flat five","notes":"A C# Eb G"},
{"root":"Bb","name":"seventh flat five","notes":"Bb D E Ab"},
{"root":"B","name":"seventh flat five","notes":"B D# F A"},
{"root":"C","name":"major seventh flat third","notes":"C Eb G B"},
{"root":"C#","name":"major seventh flat third","notes":"C# E G# C"},
{"root":"D","name":"major seventh flat third","notes":"D F A C#"},
{"root":"Eb","name":"major seventh flat third","notes":"Eb Gb Bb D"},
{"root":"E","name":"major seventh flat third","notes":"E G B D#"},
{"root":"F","name":"major seventh flat third","notes":"F Ab C E"},
{"root":"F#","name":"major seventh flat third","notes":"F# A C# F"},
{"root":"G","name":"major seventh flat third","notes":"G Bb D F#"},
{"root":"Ab","name":"major seventh flat third","notes":"Ab B Eb G"},
{"root":"A","name":"major seventh flat third","notes":"A C E G#"},
{"root":"Bb","name":"major seventh flat third","notes":"Bb Db F A"},
{"root":"B","name":"major seventh flat third","notes":"B D F# A#"},
{"root":"C","name":"minor seventh flat five","notes":"C Eb Gb Bb"},
{"root":"C#","name":"minor seventh flat five","notes":"C# E G B"},
{"root":"D","name":"minor seventh flat five","notes":"D F Ab C"},
{"root":"Eb","name":"minor seventh flat five","notes":"Eb Gb A Db"},
{"root":"E","name":"minor seventh flat five","notes":"E G Bb D"},
{"root":"F","name":"minor seventh flat five","notes":"F Ab B Eb"},
{"root":"F#","name":"minor seventh flat five","notes":"F# A C E"},
{"root":"G","name":"minor seventh flat five","notes":"G Bb Db F"},
{"root":"Ab","name":"minor seventh flat five","notes":"Ab B D Gb"},
{"root":"A","name":"minor seventh flat five","notes":"A C Eb G"},
{"root":"Bb","name":"minor seventh flat five","notes":"Bb Db E Ab"},
{"root":"B","name":"minor seventh flat five","notes":"B D F A"},
{"root":"C","name":"seventh suspended fourth","notes":"C F G Bb"},
{"root":"C#","name":"seventh suspended fourth","notes":"C# F# G# B"},
{"root":"D","name":"seventh suspended fourth","notes":"D G A C"},
{"root":"Eb","name":"seventh suspended fourth","notes":"Eb Ab Bb Db"},
{"root":"E","name":"seventh suspended fourth","notes":"E A B D"},
{"root":"F","name":"seventh suspended fourth","notes":"F Bb C Eb"},
{"root":"F#","name":"seventh suspended fourth","notes":"F# B C# E"},
{"root":"G","name":"seventh suspended fourth","notes":"G C D F"},
{"root":"Ab","name":"seventh suspended fourth","notes":"Ab Db Eb Gb"},
{"root":"A","name":"seventh suspended fourth","notes":"A D E G"},
{"root":"Bb","name":"seventh suspended fourth","notes":"Bb Eb F Ab"},
{"root":"B","name":"seventh suspended fourth","notes":"B E F# A"},
{"root":"C","name":"ninth","notes":"C E G Bb D"},
{"root":"C#","name":"ninth","notes":"C# F G# B D#"},
{"root":"D","name":"ninth","notes":"D F# A C E"},
{"root":"Eb","name":"ninth","notes":"Eb G Bb Db F"},
{"root":"E","name":"ninth","notes":"E G# B D F#"},
{"root":"F","name":"ninth","notes":"F A C Eb G"},
{"root":"F#","name":"ninth","notes":"F# A# C# E G#"},
{"root":"G","name":"ninth","notes":"G B D F A"},
{"root":"Ab","name":"ninth","notes":"Ab C Eb Gb Bb"},
{"root":"A","name":"ninth","notes":"A C# E G B"},
{"root":"Bb","name":"ninth","notes":"Bb D F Ab C"},
{"root":"B","name":"ninth","notes":"B D# F# A C#"},
{"root":"C","name":"minor ninth","notes":"C Eb G Bb D"},
{"root":"C#","name":"minor ninth","notes":"C# E G# B D#"},
{"root":"D","name":"minor ninth","notes":"D F A C E"},
{"root":"Eb","name":"minor ninth","notes":"Eb Gb Bb Db F"},
{"root":"E","name":"minor ninth","notes":"E G B D F#"},
{"root":"F","name":"minor ninth","notes":"F Ab C Eb G"},
{"root":"F#","name":"minor ninth","notes":"F# A C# E G#"},
{"root":"G","name":"minor ninth","notes":"G Bb D F A"},
{"root":"Ab","name":"minor ninth","notes":"Ab B Eb Gb Bb"},
{"root":"A","name":"minor ninth","notes":"A C E G B"},
{"root":"Bb","name":"minor ninth","notes":"Bb Db F Ab C"},
{"root":"B","name":"minor ninth","notes":"B D F# A C#"},
{"root":"C","name":"major ninth","notes":"C E G B D"},
{"root":"C#","name":"major ninth","notes":"C# F G# C D#"},
{"root":"D","name":"major ninth","notes":"D F# A C# E"},
{"root":"Eb","name":"major ninth","notes":"Eb G Bb D F"},
{"root":"E","name":"major ninth","notes":"E G# B D# F#"},
{"root":"F","name":"major ninth","notes":"F A C E G"},
{"root":"F#","name":"major ninth","notes":"F# A# C# F G#"},
{"root":"G","name":"major ninth","notes":"G B D F# A"},
{"root":"Ab","name":"major ninth","notes":"Ab C Eb G Bb"},
{"root":"A","name":"major ninth","notes":"A C# E G# B"},
{"root":"Bb","name":"major ninth","notes":"Bb D F A C"},
{"root":"B","name":"major ninth","notes":"B D# F# A# C#"},
{"root":"C","name":"ninth augmented fifth","notes":"C E G# Bb D"},
{"root":"C#","name":"ninth augmented fifth","notes":"C# F A B D#"},
{"root":"D","name":"ninth augmented fifth","notes":"D F# A# C E"},
{"root":"Eb","name":"ninth augmented fifth","notes":"Eb G B Db F"},
{"root":"E","name":"ninth augmented fifth","notes":"E G# C D F#"},
{"root":"F","name":"ninth augmented fifth","notes":"F A C# Eb G"},
{"root":"F#","name":"ninth augmented fifth","notes":"F# A# D E G#"},
{"root":"G","name":"ninth augmented fifth","notes":"G B D# F A"},
{"root":"Ab","name":"ninth augmented fifth","notes":"Ab C E Gb Bb"},
{"root":"A","name":"ninth augmented fifth","notes":"A C# F G B"},
{"root":"Bb","name":"ninth augmented fifth","notes":"Bb D F# Ab C"},
{"root":"B","name":"ninth augmented fifth","notes":"B D# G A C#"},
{"root":"C","name":"ninth flatted fifth","notes":"C E Gb Bb D"},
{"root":"C#","name":"ninth flatted fifth","notes":"C# F G B D#"},
{"root":"D","name":"ninth flatted fifth","notes":"D F# Ab C E"},
{"root":"Eb","name":"ninth flatted fifth","notes":"Eb G A Db F"},
{"root":"E","name":"ninth flatted fifth","notes":"E G# Bb D F#"},
{"root":"F","name":"ninth flatted fifth","notes":"F A B Eb G"},
{"root":"F#","name":"ninth flatted fifth","notes":"F# A# C E G#"},
{"root":"G","name":"ninth flatted fifth","notes":"G B Db F A"},
{"root":"Ab","name":"ninth flatted fifth","notes":"Ab C D Gb Bb"},
{"root":"A","name":"ninth flatted fifth","notes":"A C# Eb G B"},
{"root":"Bb","name":"ninth flatted fifth","notes":"Bb D E Ab C"},
{"root":"B","name":"ninth flatted fifth","notes":"B D# F A C#"},
{"root":"C","name":"seventh flat ninth","notes":"C E G Bb Db"},
{"root":"C#","name":"seventh flat ninth","notes":"C# F G# B D"},
{"root":"D","name":"seventh flat ninth","notes":"D F# A C Eb"},
{"root":"Eb","name":"seventh flat ninth","notes":"Eb G Bb Db E"},
{"root":"E","name":"seventh flat ninth","notes":"E G# B D F"},
{"root":"F","name":"seventh flat ninth","notes":"F A C Eb Gb"},
{"root":"F#","name":"seventh flat ninth","notes":"F# A# C# E G"},
{"root":"G","name":"seventh flat ninth","notes":"G B D F Ab"},
{"root":"Ab","name":"seventh flat ninth","notes":"Ab C Eb Gb Bbb"},
{"root":"A","name":"seventh flat ninth","notes":"A C# E G Bb"},
{"root":"Bb","name":"seventh flat ninth","notes":"Bb D F Ab B"},
{"root":"B","name":"seventh flat ninth","notes":"B D# F# A C"},
{"root":"C","name":"seventh sharp ninth","notes":"C E G Bb D#"},
{"root":"C#","name":"seventh sharp ninth","notes":"C# F G# B E"},
{"root":"D","name":"seventh sharp ninth","notes":"D F# A C F"},
{"root":"Eb","name":"seventh sharp ninth","notes":"Eb G Bb Db F#"},
{"root":"E","name":"seventh sharp ninth","notes":"E G# B D G"},
{"root":"F","name":"seventh sharp ninth","notes":"F A C Eb G#"},
{"root":"F#","name":"seventh sharp ninth","notes":"F# A# C# E A"},
{"root":"G","name":"seventh sharp ninth","notes":"G B D F A#"},
{"root":"Ab","name":"seventh sharp ninth","notes":"Ab C Eb Gb B"},
{"root":"A","name":"seventh sharp ninth","notes":"A C# E G C"},
{"root":"Bb","name":"seventh sharp ninth","notes":"Bb D F Ab C#"},
{"root":"B","name":"seventh sharp ninth","notes":"B D# F# A D"},
{"root":"C6","name":"add 9","notes":"C E G A D"},
{"root":"C#","name":"6 add 9","notes":"C# F G# A# D#"},
{"root":"D","name":"6 add 9","notes":"D F# A B E"},
{"root":"Eb","name":"6 add 9","notes":"Eb G Bb C F"},
{"root":"E","name":"6 add 9","notes":"E G# B C# F#"},
{"root":"F","name":"6 add 9","notes":"F A C D G"},
{"root":"F#","name":"6 add 9","notes":"F# A# C# D# G#"},
{"root":"G","name":"6 add 9","notes":"G B D E A"},
{"root":"Ab","name":"6 add 9","notes":"Ab C Eb F Bb"},
{"root":"A","name":"6 add 9","notes":"A C# E F# B"},
{"root":"Bb","name":"6 add 9","notes":"Bb D F G C"},
{"root":"B","name":"6 add 9","notes":"B D# F# G# C#"},
{"root":"C","name":"eleventh","notes":"C E G Bb D F"},
{"root":"C#","name":"eleventh","notes":"C# F G# B D# F#"},
{"root":"D","name":"eleventh","notes":"D F# A C E G"},
{"root":"Eb","name":"eleventh","notes":"Eb G Bb Db F Ab"},
{"root":"E","name":"eleventh","notes":"E G# B D F# A"},
{"root":"F","name":"eleventh","notes":"F A C Eb G Bb"},
{"root":"F#","name":"eleventh","notes":"F# A# C# E G# B"},
{"root":"G","name":"eleventh","notes":"G B D F A C"},
{"root":"Ab","name":"eleventh","notes":"Ab C Eb Gb Bb Db"},
{"root":"A","name":"eleventh","notes":"A C# E G B D"},
{"root":"Bb","name":"eleventh","notes":"Bb D F Ab C Eb"},
{"root":"B","name":"eleventh","notes":"B D# F# A C# E"},
{"root":"C","name":"augmented eleventh","notes":"C E G Bb D F#"},
{"root":"C#","name":"augmented eleventh","notes":"C# F G# B D# G"},
{"root":"D","name":"augmented eleventh","notes":"D F# A C E G#"},
{"root":"Eb","name":"augmented eleventh","notes":"Eb G Bb Db F A"},
{"root":"E","name":"augmented eleventh","notes":"E G# B D F# A#"},
{"root":"F","name":"augmented eleventh","notes":"F A C Eb G B"},
{"root":"F#","name":"augmented eleventh","notes":"F# A# C# E G# C"},
{"root":"G","name":"augmented eleventh","notes":"G B D F A C#"},
{"root":"Ab","name":"augmented eleventh","notes":"Ab C Eb Gb Bb D"},
{"root":"A","name":"augmented eleventh","notes":"A C# E G B D#"},
{"root":"Bb","name":"augmented eleventh","notes":"Bb D F Ab C E"},
{"root":"B","name":"augmented eleventh","notes":"B D# F# A C# F"},
{"root":"C","name":"thirteenth","notes":"C E G Bb D F A"},
{"root":"C#","name":"thirteenth","notes":"C# F G# B D# F# A#"},
{"root":"D","name":"thirteenth","notes":"D F# A C E G B"},
{"root":"Eb","name":"thirteenth","notes":"Eb G Bb Db F Ab C"},
{"root":"E","name":"thirteenth","notes":"E G# B D F# A C#"},
{"root":"F","name":"thirteenth","notes":"F A C Eb G Bb D"},
{"root":"F#","name":"thirteenth","notes":"F# A# C# E G# B D#"},
{"root":"G","name":"thirteenth","notes":"G B D F A C E"},
{"root":"Ab","name":"thirteenth","notes":"Ab C Eb Gb Bb Db F"},
{"root":"A","name":"thirteenth","notes":"A C# E G B D F#"},
{"root":"Bb","name":"thirteenth","notes":"Bb D F Ab C Eb G"},
{"root":"B","name":"thirteenth","notes":"B D# F# A C# E G#"},
{"root":"C","name":"thirteenth flat ninth","notes":"C E G Bb Db F A"},
{"root":"C#","name":"thirteenth flat ninth","notes":"C# F G# B D F# A#"},
{"root":"D","name":"thirteenth flat ninth","notes":"D F# A C Eb G B"},
{"root":"Eb","name":"thirteenth flat ninth","notes":"Eb G Bb Db E Ab C"},
{"root":"E","name":"thirteenth flat ninth","notes":"E G# B D F A C#"},
{"root":"F","name":"thirteenth flat ninth","notes":"F A C Eb Gb Bb D"},
{"root":"F#","name":"thirteenth flat ninth","notes":"F# A# C# E G B D#"},
{"root":"G","name":"thirteenth flat ninth","notes":"G B D F Ab C E"},
{"root":"Ab","name":"thirteenth flat ninth","notes":"Ab C Eb Gb A Db F"},
{"root":"A","name":"thirteenth flat ninth","notes":"A C# E G Bb D F#"},
{"root":"Bb","name":"thirteenth flat ninth","notes":"Bb D F Ab B Eb G"},
{"root":"B","name":"thirteenth flat ninth","notes":"B D# F# A C E G#"},
{"root":"C","name":"thirteenth flat ninth flat fifth","notes":"C E Gb Bb Db F A"},
{"root":"C#","name":"thirteenth flat ninth flat fifth","notes":"C# F G B D F# A#"},
{"root":"D","name":"thirteenth flat ninth flat fifth","notes":"D F# Ab C Eb G B"},
{"root":"Eb","name":"thirteenth flat ninth flat fifth","notes":"Eb G A Db E Ab C"},
{"root":"E","name":"thirteenth flat ninth flat fifth","notes":"E G# Bb D F A C#"},
{"root":"F","name":"thirteenth flat ninth flat fifth","notes":"F A B Eb Gb Bb D"},
{"root":"F#","name":"thirteenth flat ninth flat fifth","notes":"F# A# C E G B D#"},
{"root":"G","name":"thirteenth flat ninth flat fifth","notes":"G B Db F Ab C E"},
{"root":"Ab","name":"thirteenth flat ninth flat fifth","notes":"Ab C D Gb A Db F"},
{"root":"A","name":"thirteenth flat ninth flat fifth","notes":"A C# Eb G Bb D F#"},
{"root":"Bb","name":"thirteenth flat ninth flat fifth","notes":"Bb D E Ab B Eb G"},
{"root":"B","name":"thirteenth flat ninth flat fifth","notes":"B D# F A C E G#"},
{"root":"C","name":"half diminished","notes":"C Eb Gb Bb"},
{"root":"C#","name":"half diminished","notes":"C# E G B"},
{"root":"D","name":"half diminished","notes":"D F Ab C"},
{"root":"Eb","name":"half diminished","notes":"Eb Gb A D"},
{"root":"E","name":"half diminished","notes":"E G Bb D"},
{"root":"F","name":"half diminished","notes":"F Ab B Eb"},
{"root":"F#","name":"half diminished","notes":"F# A C E"},
{"root":"G","name":"half diminished","notes":"G Bb Db F"},
{"root":"Ab","name":"half diminished","notes":"Ab B D Gb"},
{"root":"A","name":"half diminished","notes":"A C Eb G"},
{"root":"Bb","name":"half diminished","notes":"Bb Db E Ab"},
{"root":"B","name":"half diminished","notes":"B D F A"}
    ]